name = "promptverse"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-10-06"

pages_build_output_dir = ".vercel/output/static"

[observability]
enabled = true

[env.production]
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "promptverse-db-local"
database_id = "dd03f7fc-70c1-4fc5-b23d-5f6fc3168aa4"
preview_database_id = "dd03f7fc-70c1-4fc5-b23d-5f6fc3168aa4"

[[kv_namespaces]]
binding = "CACHE"
id = "839e3add7bda4fbc9c78f6ed57caaf2e"