name = "promptverse"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-10-06"

pages_build_output_dir = ".vercel/output/static"

[observability]
enabled = true

[env.production]
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "promptverse_d1_db"
database_name = "promptverse-db"
database_id = "95026327-75e5-4534-ba83-5d9c8b5df0ec"


[[kv_namespaces]]
binding = "promptverse_kv"
id = "839e3add7bda4fbc9c78f6ed57caaf2e"

[env.preview]
compatibility_flags = ["nodejs_compat"]

[[env.preview.d1_databases]]
binding = "promptverse_d1_db"
database_name = "promptverse-db"
database_id = "95026327-75e5-4534-ba83-5d9c8b5df0ec"

[[env.preview.kv_namespaces]]
binding = "promptverse_kv"
id = "839e3add7bda4fbc9c78f6ed57caaf2e"