name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      AI_BASE_URL: ${{ secrets.AI_BASE_URL }}
      AI_API_KEY: ${{ secrets.AI_API_KEY }}
      LONGCAT_KEY: ${{ secrets.LONGCAT_KEY }}
      PROXY_TOKEN: ${{ secrets.PROXY_TOKEN }}
      AI_MODEL: ${{ secrets.AI_MODEL }}
      ADMIN_SEED_TOKEN: ${{ secrets.ADMIN_SEED_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Cloudflare output
        run: npm run build:cloudflare

      - name: Deploy to Cloudflare Pages
        run: npm run deploy
